name: sushi

on: [push]
jobs:
  lint:
    name: Check sushi
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install modules
        run: npm install -g fsh-sushi
      - name: Run sushi
        run: sushi .